# Adapted from https://github.com/JamesIves/github-pages-deploy-action
name: Build and Deploy Scroll
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          npm install .
          sudo apt-get install cloc
          npm run build
          # The line below is needed if you have *.html in your gitignore file
          rm .gitignore
          # We want to check in the monaco-editor so it is available on the built site
          git add -f node_modules/monaco-editor
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: wws # The branch the action should deploy to.
          folder: .
